### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-MLR062998#2]
[Infografia (Gestion de proyectos).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-MLR062998/files/12471519/Infografia.Gestion.de.proyectos.pdf)

**Comment by KarlaV0** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
